export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

alias ls='ls -G'
alias vi='/usr/bin/vim'
alias gitx='/Applications/GitX.app/Contents/Resources/gitx'

export PS1="\u@\h\w$ "
